name: Tag & Note Release
on : 
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  CheckRelease:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check if merge is release branch
        id: check-release
        run: |
          if [[ ${{ github.head_ref }} =~ ^rel/([0-9]+\.[0-9]+\.[0-9]+$) ]]; then
            echo "match=true" >> $GITHUB_OUTPUT
            echo "version=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.pull_request.merged }}" != "true" ]] ; then
            FAILURE_MESSAGE='Tag if release branch'
            echo "FAILURE_MESSAGE=${FAILURE_MESSAGE}" >> "$GITHUB_ENV"
            echo "::error::${FAILURE_MESSAGE}" ; exit 1
          fi
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'
      - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: version bump to ${{ steps.check-release.outputs.version }}
          tagging_message: '${{ steps.check-release.outputs.version }}'
      - uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with: 
          tag: ${{ steps.check-release.outputs.version }}
          prerelease: true
          generateReleaseNotes: true

